### ISSUE TITLE
How to choose priorities

### ISSUE THREAD

**Issue by martindrech** [duncanhawthorne/drupebox#2]
Hi. I am finding the following problem: when syncing, the script gives priority of the remote file over my local file. 

An example: I have a log.txt and modify it in the local folder with a new line. When I run drupebox.py, the script downloads the file from Dropbox and overwrites the local file, therefore loosing the last log.

Would you know how to avoid this, and give priority over my local file?

Thank you!

**Comment by duncanhawthorne** [comment]
Hi, thanks for your feedback. 

Yes, Drupebox shouldn't be doing that. Priority should be based on the most recent file to be updated. If the local file has been modified after the file stored on Dropbox was last modified, then the local file should take priority and upload. Possibly the problem is being caused by a timezone issue which is making that comparison not work correctly. I have just updated the Drupebox code on github which may fix this issue for you (run "git pull" in the Drupebox folder to get the new code). 

Does the updated code fix things for you? If not, could you run drupebox and copy and paste the output from the terminal? This may shed light on the problem.

**Comment by martindrech** [comment]
Hi, thank you for the quick reply. 
I have just tried the new script, and it seems to be working correctly now. I will keep an eye but it seems the issue was what you suspected. 

Again thanks, great work!
